# Generated by Django 6.0.3 on 2026-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('pdf', 'PDF'), ('url', 'Site Web')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
