# Generated by Django 6.0.3 on 2026-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('orange_money', 'Orange Money'), ('paydunya', 'PayDunya'), ('cinetpay', 'CinetPay')], max_length=20),
        ),
    ]
