# Generated by Django 6.0.3 on 2026-03-28 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('gpt', 'GPT (OpenAI)')], default='claude', max_length=20)),
                ('system_prompt', models.TextField(blank=True, default='Tu es un assistant utile et professionnel.')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('so', 'Soussou'), ('pu', 'Pular'), ('ma', 'Malinké')], default='fr', max_length=5)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bot_logos/')),
                ('widget_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
